# Generated by Django 5.2.3 on 2025-06-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('raza', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('tamaño', models.CharField(choices=[('S', 'Pequeño'), ('M', 'Mediano'), ('L', 'Grande'), ('X', 'Extra Grande')], max_length=1)),
                ('peso', models.FloatField()),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], max_length=1)),
                ('estado_salud', models.CharField(max_length=100)),
                ('vacunado', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('reservado', 'Reservado'), ('adoptado', 'Adoptado')], default='disponible', max_length=20)),
                ('temperamento', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioAdoptante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('raza_preferida', models.CharField(max_length=100)),
                ('edad_preferida', models.IntegerField()),
                ('tamaño_preferido', models.CharField(choices=[('S', 'Pequeño'), ('M', 'Mediano'), ('L', 'Grande'), ('X', 'Extra Grande')], max_length=1)),
                ('historial_adopciones', models.ManyToManyField(blank=True, to='perros.perro')),
            ],
        ),
    ]
